z_dim: ${target.z_dim}
epsilon_dim: ${target.epsilon_dim}
hidden_dim: 32
num_layers: 8
logit: ${vi_model.uniform}
device: ${device}
use_optimizer: true
warmup:
  enabled: true
  lr: 1.0e-2
  batch_size: 8192
  epochs: 500
  kl_log_freq: 10
  loss_log_freq: 100